import { Expert } from './types';

export const EXPERTS: Expert[] = [
  {
    id: 'ki-waskita',
    name: 'Ki Waskita',
    title: 'Pakar Budaya Jawa',
    experience: 'Penjaga Kebijaksanaan Jawa',
    avatarUrl: 'https://i.pravatar.cc/200?u=ki-waskita',
    bio: "Ki Waskita adalah ahli filosofi dan tata krama Jawa. Namanya, yang berarti 'bijaksana' dan 'tajam penglihatan', mencerminkan pemahamannya yang mendalam tentang ajaran luhur dan etika Jawa.",
    specialties: ['Filosofi Jawa', 'Tata Krama', 'Sastra Kuno', 'Kebijaksanaan'],
  },
  {
    id: 'ambu-pangeusi',
    name: 'Ambu Pangeusi',
    title: 'Pakar Budaya Sunda',
    experience: 'Pengayom Tradisi Pasundan',
    avatarUrl: 'https://i.pravatar.cc/200?u=ambu-pangeusi',
    bio: "Ambu Pangeusi adalah sosok 'Ibu Penjaga' tradisi Sunda. Ia dikenal teduh dan mengayomi, memiliki pengetahuan luas tentang kearifan lokal, sastra, dan adat istiadat Pasundan.",
    specialties: ['Adat Sunda', 'Kearifan Lokal', 'Sastra Lisan', 'Mengayomi'],
  },
  {
    id: 'tuan-pustaka',
    name: 'Tuan Pustaka',
    title: 'Pakar Budaya Melayu',
    experience: 'Sumber Ilmu Sastra Melayu',
    avatarUrl: 'https://i.pravatar.cc/200?u=tuan-pustaka',
    bio: "Tuan Pustaka adalah sumber ilmu budaya Melayu yang dihormati. Keahliannya terbentang luas dari sastra, pantun, hingga sejarah maritim. Ia adalah penjaga khazanah intelektual peradaban Melayu.",
    specialties: ['Sastra Melayu', 'Pantun', 'Sejarah Maritim', 'Adab'],
  },
  {
    id: 'oppung-hasian',
    name: 'Oppung Hasian',
    title: 'Pakar Budaya Batak',
    experience: 'Penjaga Silsilah & Adat',
    avatarUrl: 'https://i.pravatar.cc/200?u=oppung-hasian',
    bio: "Oppung Hasian, sang 'Kakek Kesayangan', adalah ahli dalam silsilah (tarombo) dan adat perkawinan Batak. Ia memegang teguh nilai-nilai kekerabatan dan kasih sayang dalam budaya Batak.",
    specialties: ['Tarombo (Silsilah)', 'Adat Perkawinan', 'Falsafah Batak', 'Kekerabatan'],
  },
  {
    id: 'ra-tretan',
    name: 'Ra Tretan',
    title: 'Pakar Budaya Madura',
    experience: 'Simbol Persaudaraan Madura',
    avatarUrl: 'https://i.pravatar.cc/200?u=ra-tretan',
    bio: "Ra Tretan merepresentasikan kebangsawanan dan persaudaraan ('Tretan Dhibi'). Ia adalah ahli dalam etos kerja, tradisi Carok, serta budaya pesisir yang kuat dan tegas.",
    specialties: ['Etos Kerja', 'Tradisi Carok', 'Budaya Pesisir', 'Persaudaraan'],
  },
  {
    id: 'encang-jago',
    name: 'Encang Jago',
    title: 'Pakar Budaya Betawi',
    experience: 'Jawara Dialek & Humor',
    avatarUrl: 'https://i.pravatar.cc/200?u=encang-jago',
    bio: "Encang Jago, sang 'Paman Ahli', adalah pribadi yang humoris dan ahli dialek Betawi. Ia memahami seluk-beluk lenong, ondel-ondel, dan kehidupan urban masyarakat Betawi.",
    specialties: ['Dialek Betawi', 'Lenong', 'Ondel-Ondel', 'Humor Betawi'],
  },
  {
    id: 'bundo-cadiak',
    name: 'Bundo Cadiak',
    title: 'Pakar Budaya Minangkabau',
    experience: 'Penjaga Adat Matrilineal',
    avatarUrl: 'https://i.pravatar.cc/200?u=bundo-cadiak',
    bio: "Bundo Cadiak, 'Ibu yang Cerdik', adalah ahli dalam adat matrilineal Minangkabau. Ia memiliki pemahaman mendalam tentang filosofi merantau, surau, dan pepatah-petitih bijak.",
    specialties: ['Adat Matrilineal', 'Filosofi Merantau', 'Pepatah-Petitih', 'Kuliner Rendang'],
  },
  {
    id: 'datu-lontara',
    name: 'Datu Lontara',
    title: 'Pakar Budaya Bugis',
    experience: 'Ahli Naskah Kuno & Pelayaran',
    avatarUrl: 'https://i.pravatar.cc/200?u=datu-lontara',
    bio: "Datu Lontara adalah penjaga naskah kuno (Lontara) Bugis. Sebagai bangsawan terpelajar, ia ahli dalam etika 'Siri Na Pacce', serta pengetahuan tentang pelayaran dan navigasi tradisional.",
    specialties: ['Aksara Lontara', 'Siri Na Pacce', 'Pelayaran', 'Navigasi Tradisional'],
  },
  {
    id: 'dangsanak-bauntung',
    name: 'Dangsanak Bauntung',
    title: 'Pakar Budaya Banjar',
    experience: 'Ahli Budaya Sungai',
    avatarUrl: 'https://i.pravatar.cc/200?u=dangsanak-bauntung',
    bio: "Dangsanak Bauntung, 'Saudara yang Beruntung', adalah ahli budaya sungai Banjar. Ia memahami denyut kehidupan di pasar terapung, arsitektur rumah panggung, dan ritual keagamaan yang unik.",
    specialties: ['Pasar Terapung', 'Arsitektur Banjar', 'Ritual Keagamaan', 'Budaya Sungai'],
  },
  {
    id: 'jero-suara',
    name: 'Jero Suara',
    title: 'Pakar Budaya Bali',
    experience: 'Penyampai Pesan Spiritual',
    avatarUrl: 'https://i.pravatar.cc/200?u=jero-suara',
    bio: "Jero Suara adalah sosok terhormat yang ahli dalam filosofi Tri Hita Karana. Ia mampu menyampaikan pesan dan ujaran spiritual Bali dengan jelas, serta memahami makna di balik setiap ritual Hindu Bali.",
    specialties: ['Tri Hita Karana', 'Ritual Hindu Bali', 'Seni Ukir', 'Subak'],
  },
  {
    id: 'teuku-hikayat',
    name: 'Teuku Hikayat',
    title: 'Pakar Budaya Aceh',
    experience: 'Penutur Kisah Heroik',
    avatarUrl: 'https://i.pravatar.cc/200?u=teuku-hikayat',
    bio: "Teuku Hikayat, seorang bangsawan penutur, adalah ahli dalam sejarah heroik dan hikayat Aceh. Ia memiliki pemahaman mendalam tentang penerapan Syariat Islam dan semangat perjuangan rakyat Serambi Mekkah.",
    specialties: ['Hikayat Aceh', 'Sejarah Heroik', 'Syariat Islam', 'Tari Saman'],
  },
  {
    id: 'panglima-borneo',
    name: 'Panglima Borneo',
    title: 'Pakar Budaya Dayak',
    experience: 'Penjaga Hutan & Tradisi',
    avatarUrl: 'https://i.pravatar.cc/200?u=panglima-borneo',
    bio: "Panglima Borneo adalah pemimpin yang arif dan penjaga tradisi Dayak. Ia memiliki pengetahuan luas tentang alam, obat-obatan tradisional dari hutan, seni ukir, dan filosofi Rumah Betang.",
    specialties: ['Alam & Hutan', 'Obat Tradisional', 'Seni Ukir Dayak', 'Hukum Adat'],
  },
  {
    id: 'inaq-sasak',
    name: 'Inaq Sasak',
    title: 'Pakar Budaya Sasak',
    experience: 'Ahli Tenun & Tradisi Lombok',
    avatarUrl: 'https://i.pravatar.cc/200?u=inaq-sasak',
    bio: "Inaq Sasak, sang 'Ibu Suku Sasak', adalah ahli dalam seni tenun songket yang rumit. Ia memahami tradisi pernikahan 'merariq' dan legenda suci yang menyelimuti Gunung Rinjani.",
    specialties: ['Tenun Songket', 'Tradisi Merariq', 'Legenda Rinjani', 'Kuliner Ayam Taliwang'],
  },
  {
    id: 'kongco-kesenian',
    name: 'Kongco Kesenian',
    title: 'Pakar Budaya Tionghoa-Indonesia',
    experience: 'Ahli Akulturasi Budaya',
    avatarUrl: 'https://i.pravatar.cc/200?u=kongco-kesenian',
    bio: "Kongco Kesenian adalah sosok leluhur bijak yang ahli dalam perpaduan budaya Tionghoa dan Indonesia. Ia memahami filosofi di balik perayaan Imlek, barongsai, hingga kuliner peranakan.",
    specialties: ['Akulturasi Budaya', 'Kuliner Peranakan', 'Tradisi Imlek', 'Barongsai'],
  },
  {
    id: 'karaeng-pabale',
    name: 'Karaeng Pa\'bale',
    title: 'Pakar Budaya Makassar',
    experience: 'Pemimpin Pelaut Ulung',
    avatarUrl: 'https://i.pravatar.cc/200?u=karaeng-pabale',
    bio: "Karaeng Pa'bale, 'Raja yang Berlayar', adalah ahli maritim dan pelabuhan dari Makassar. Ia memahami seluk-beluk pembuatan perahu Phinisi yang legendaris dan semangat bahari orang Makassar.",
    specialties: ['Maritim', 'Perahu Phinisi', 'Budaya Pelabuhan', 'Sejarah Gowa-Tallo'],
  },
  {
    id: 'ki-dalang-cirebon',
    name: 'Ki Dalang Cirebon',
    title: 'Pakar Budaya Cirebon',
    experience: 'Maestro Seni Pesisiran',
    avatarUrl: 'https://i.pravatar.cc/200?u=ki-dalang-cirebon',
    bio: "Ki Dalang adalah maestro seni Cirebon yang memahami percampuran budaya Jawa dan Sunda. Ia ahli dalam wayang kulit Cirebon, tari Topeng, dan seni batik Megamendung yang khas.",
    specialties: ['Wayang Cirebon', 'Tari Topeng', 'Batik Megamendung', 'Sintren'],
  },
  {
    id: 'penyimbang-sai',
    name: 'Penyimbang Sai',
    title: 'Pakar Budaya Lampung',
    experience: 'Pemangku Adat Tertinggi',
    avatarUrl: 'https://i.pravatar.cc/200?u=penyimbang-sai',
    bio: "Penyimbang Sai, 'Pemangku Adat yang Satu', adalah ahli dalam sistem adat Penyimbang. Ia memiliki pengetahuan mendalam tentang kain Tapis Lampung, aksara Kaganga, dan falsafah 'Piil Pesenggiri'.",
    specialties: ['Sistem Penyimbang', 'Kain Tapis', 'Aksara Kaganga', 'Piil Pesenggiri'],
  },
  {
    id: 'opu-motololo',
    name: 'Opu Motololo',
    title: 'Pakar Budaya Gorontalo',
    experience: 'Penjaga Adat & Kesetiaan',
    avatarUrl: 'https://i.pravatar.cc/200?u=opu-motololo',
    bio: "Opu Motololo adalah sosok terhormat yang setia menjaga adat Gorontalo. Ia ahli dalam filosofi 'Adat Bersendikan Syara, Syara Bersendikan Kitabullah' dan tradisi pernikahan yang unik.",
    specialties: ['Adat Pernikahan', 'Filosofi Adat', 'Karawo', 'Hukum Islam Lokal'],
  },
  {
    id: 'tonaas-waruga',
    name: 'Tonaas Waruga',
    title: 'Pakar Budaya Minahasa',
    experience: 'Pembimbing Adat & Warisan',
    avatarUrl: 'https://i.pravatar.cc/200?u=tonaas-waruga',
    bio: "Tonaas Waruga adalah pemimpin adat Minahasa yang memahami warisan leluhur. Ia ahli dalam peninggalan kubur batu Waruga, tari perang Kabasaran, dan kuliner Minahasa yang kaya rasa.",
    specialties: ['Waruga', 'Tari Kabasaran', 'Kuliner Minahasa', 'Mapalus'],
  },
  {
    id: 'si-ulu-faulu',
    name: 'Si Ulu Fa\'ulu',
    title: 'Pakar Budaya Nias',
    experience: 'Pemimpin Terbaik Nias',
    avatarUrl: 'https://i.pravatar.cc/200?u=si-ulu-faulu',
    bio: "Si Ulu Fa'ulu, 'Pemimpin Terbaik', adalah ahli dalam budaya Nias yang kaya. Ia memahami makna di balik tradisi lompat batu (Hombo Batu), seni ukir, dan sistem kasta tradisional yang kompleks.",
    specialties: ['Hombo Batu', 'Seni Ukir Nias', 'Sistem Kasta', 'Arsitektur Omo Hada'],
  },
  {
    id: 'lakina-kamali',
    name: 'Lakina Kamali',
    title: 'Pakar Budaya Buton',
    experience: 'Ahli Sejarah Kesultanan',
    avatarUrl: 'https://i.pravatar.cc/200?u=lakina-kamali',
    bio: "Lakina Kamali, 'Raja di Istana', adalah ahli sejarah Kesultanan Buton. Ia memiliki pengetahuan tentang benteng pertahanan terluas di dunia dan sistem pemerintahan 'Martabat Tujuh'.",
    specialties: ['Kesultanan Buton', 'Benteng Keraton', 'Martabat Tujuh', 'Sejarah Maritim'],
  },
  {
    id: 'nai-feto',
    name: 'Nai Feto',
    title: 'Pakar Budaya Atoni',
    experience: 'Ibu Penjaga Tenun Ikat',
    avatarUrl: 'https://i.pravatar.cc/200?u=nai-feto',
    bio: "Nai Feto, 'Ibu Perempuan', adalah ahli dalam tradisi Suku Atoni di Timor. Ia adalah penjaga teknik tenun ikat yang sakral dan memahami tradisi menjaga lumbung pangan sebagai pusat kehidupan.",
    specialties: ['Tenun Ikat Timor', 'Lumbung Pangan', 'Tradisi Lisan', 'Arsitektur Ume Kbubu'],
  },
  {
    id: 'pong-banne',
    name: 'Pong Banne',
    title: 'Pakar Budaya Toraja',
    experience: 'Ahli Upacara & Filosofi',
    avatarUrl: 'https://i.pravatar.cc/200?u=pong-banne',
    bio: "Pong Banne adalah sosok terhormat yang memegang jiwa dan roh tradisi Toraja. Ia ahli dalam upacara kematian (Rambu Solo') dan filosofi mendalam di balik arsitektur rumah Tongkonan.",
    specialties: ['Rambu Solo\'', 'Arsitektur Tongkonan', 'Seni Ukir Toraja', 'Filosofi Aluk Todolo'],
  },
  {
    id: 'magau-vunja',
    name: 'Magau Vunja',
    title: 'Pakar Budaya Kaili',
    experience: 'Raja Tanah Asal',
    avatarUrl: 'https://i.pravatar.cc/200?u=magau-vunja',
    bio: "Magau Vunja, 'Raja dari Tanah Asal', adalah ahli dalam budaya Suku Kaili. Ia memahami dialek Leddo yang khas, seni Tari Lego-lego, dan upacara adat yang berkaitan dengan alam.",
    specialties: ['Bahasa Leddo', 'Tari Lego-lego', 'Upacara Adat', 'Musik Lalove'],
  }
];
